name: Convert JSON to Markdown Daily

on:
  schedule:
    # Schedule to run daily at 3 AM UTC (which is 10 PM EST the previous day)
    - cron: '0 3 * * *'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Run conversion script
      run: python create_posts.py
