title: News Déjà Vu
author: 
  name: NewsDejaVu on GitHub
  # email: newsdejavu.dellresearch@gmail.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Description and Disclaimer:
  The News Déjà Vu website uses a large language model to select 
  a historical news article that is similar in its use of language 
  to a modern news article, after names of people, locations, and 
  organizations have been masked. The language model captures similarities 
  in the semantics of how things are described, which may or may not 
  reflect similarities in the underlying events or situations 
  being described. While the historical news articles are drawn from 
  mainstream news wires, they reflect the norms and biases of their time 
  and may be considered offensive or contain inaccurate information.

# Build settings

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives

# Theme-specific settings

minima:
  skin: classic
  # date_format: "%B %-d, %Y"
  social_links:
    - platform: github  # same as SVG filename.
      user_url: "https://github.com/NewsDejaVu/NewsDejaVu.github.io"  # URL of profile page.
      title:  Check Us Out on Github  # Optional. Text displayed on hovering over link.

header_pages:
  - about.md
  - archive.md
  - tag.md
  # - category.md # add back once we decide what we want to do with this page
  - search_bar.md

google_analytics: G-MZCLNR9M8W

show_excerpts: true

paginate: 4
paginate_path: "/blog/page:num/"

jekyll-archives:
  enabled:
  - month
  - tags
  - categories
  layouts:
    month: month-archive
    category: category-archive
    tag: tag-archive
  permalinks:
    month: '/archives/month/:year-:month/'
    tag: '/archives/tag/:name/'
    category: '/archives/category/:name/'
