title: News Déjà Vu
# Changed the html for this in the header b/c want to do more customization
# text after name will not display b/c commented out that section in the html 
author: 
  name: NewsDejaVu on Github
#   # email: newsdejavu.dellresearch@gmail.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Welcome to News Déjà Vu! This website uses a large language model to select 
  a historical news article that is similar in its use of language 
  to a modern news article, after names of people, locations, and 
  organizations have been masked. The language model captures similarities 
  in the semantics of how things are described, which may or may not 
  reflect similarities in the underlying events or situations 
  being described. Please enjoy!

# Build settings

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives

# Theme-specific settings

minima:
  skin: classic
  # date_format: "%B %-d, %Y"
  social_links:
    - platform: github  # same as SVG filename.
      user_url: "https://github.com/NewsDejaVu/NewsDejaVu.github.io"  # URL of profile page.
      title:  Check Out NewsDejaVu on Github  # Optional. Text displayed on hovering over link.

header_pages:
  - search_bar.md
  - news.md
  - editorials.md
  - advice.md
  - category.md # Entities page 
  - tag.md
  - archive.md
  - about.md
  - contributors.md

google_analytics: G-MZCLNR9M8W

show_excerpts: true

# paginate: 5
# paginate_path: "/blog/page:num/"

jekyll-archives:
  enabled:
  - month
  - tags
  - categories
  layouts:
    month: month-archive
    category: category-archive
    tag: tag-archive
  permalinks:
    month: '/archives/month/:year-:month/'
    tag: '/archives/tag/:name/'
    category: '/archives/category/:name/'
