title: News Deja Vu
author: 
  name: NewsDejaVu
  email: newsdejavu.dellresearch@gmail.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Write an awesome description for your new site here. You can edit this line
  in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

# Build settings

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

minima:
  skin: solarized-light
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
    - { platform: x,              user_url: "https://x.com/jekyllrb" }
    - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
    - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
    - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
    - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
    - { platform: github,         user_url: "https://github.com/jekyll/minima" }

header_pages:
  - about.md

show_excerpts: true
